# Generated by Django 5.2 on 2025-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='modified_file',
            field=models.FileField(blank=True, null=True, upload_to='modified_cvs/'),
        ),
    ]
